### PR TITLE
fix: Properly include css

### PR DESCRIPTION
**Pull request by alexanderGugel**
This hasn't been rebased properly.

It would be really awesome if you could finish this within the next week(s). This branch no longer "just" addresses the issues that led to its development in the first place and it makes it really hard to collaborate in any meaningful way, since it will be a nightmare to rebase. E.g. currently there are probably more than a couple of instances where stuff hasn't been rebased properly.

Also it would be awesome if you could fix your .vimrc to remove trailing whitespace. It really leads to a ton of commit noise and is annoying for people using a real editor :neutral_face:. E.g. some editors remove it automatically (see https://github.com/Famous/engine/pull/88/files), which changes the `git blame` for no good reason.

### CODE REVIEW

**Comment by DnMllr** [comment]
@alexanderGugel or, alternatively, you could set your editor to not care at all about whitespace like mine and avoid that commit noise.

**Comment by alexanderGugel** [comment]
@DnMllr I did so, but as in the PR I linked, most people don't.

**Comment by alexanderGugel** [comment]
@DnMllr This PR is really not about trailing whitespace.

I really don't want to start a discussion about trailing whitespace. It's generally accepted that it's [bad practice](https://www.google.nl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=why%20trailing%20whitespace%20is%20bad). Just a minor thing, but it would be great if we could follow conventions here.

**Comment by alexanderGugel** [comment]
Fixed in upstream. Would be really cool if you could add this to your .vimrc: http://stackoverflow.com/a/1618401/3773544 Thanks.

**Pull request closed without merging**
